# Generated by Django 3.2.10 on 2022-11-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
