# Generated by Django 3.2.10 on 2022-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221129_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Downloads',
            new_name='Download',
        ),
        migrations.AlterField(
            model_name='profile',
            name='no_of_downloads',
            field=models.IntegerField(),
        ),
    ]
