# Generated by Django 4.1.2 on 2022-11-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221129_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Download',
            new_name='DownloadCount',
        ),
    ]
