# Generated by Django 4.1.2 on 2022-12-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_download_downloadcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='no_of_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
